language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:~/nginx/sbin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl
    - LISP=ccl

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/master/scripts/install-for-ci.sh | sh

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp
    
script:
  - echo '(handler-case (progn (ql:quickload :weblocks-test)
                               (weblocks-test:test-weblocks))
              (t () (uiop:quit 1)))' | ros run

