language: common-lisp
# Sudo is required to install Roswell and some Lisp implementations
sudo: true

env:
  global:
    - PATH=~/.roswell/bin:$PATH
    - CL_SOURCE_REGISTRY="$(pwd)//"
  matrix:
    # Supported implementations
    - LISP=ccl
    - LISP=sbcl

    # Unsupported implementations
    # unable to find libssl.so, I tried hard, but it doesn't see it
    #- LISP=allegro
    # fails with mmap: Invalid argument
    #            ensure_space: Failed to validate 0 bytes at 0x58100000
    #- LISP=cmucl
    # shows error there is no package with name "UIOP"
    #- LISP=clisp
    # it shows success but actually fails with tracebacks
    #- LISP=abcl
    # compile error on loading yaclml-20150709-git
    #- LISP=ecl

matrix:
  allow_failures:
    - env: LISP=allegro
    - env: LISP=cmucl
    - env: LISP=clisp
    - env: LISP=abcl
    - env: LISP=ecl
    - env: LISP=sbcl

addons:
  apt:
    packages:
      - libtidy-dev
      - libc6-i386
      - openjdk-7-jre
      - python-pip
      
install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/master/scripts/install-for-ci.sh | sh

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp

before_script:
  - env | sort
  - cat /proc/meminfo
  - ros --version
  - ros install asdf/3.3.1.1
  # Version fixed for more build stability
  # TODO: update it from time to time
  - ros install svetlyak40wt/qlot/stable
  - ros config
  
  - qlot install
  - qlot exec ros install rove
  - qlot exec ros install cl-info
  - qlot exec ros run -e '(progn (ql:quickload :weblocks-test) (uiop:quit 0))'
  - qlot exec cl-info hamcrest rove dissect weblocks
    
  
script:
  - qlot exec rove weblocks-test.asd
  - qlot exec ./check-quickstart.ros
  - ./build-docs-on-ci.sh

