language: common-lisp
sudo: false

env:
  global:
    - PATH=~/.roswell/bin:~/nginx/sbin:$PATH
    - ROSWELL_INSTALL_DIR=$HOME/.roswell
  matrix:
    - LISP=sbcl
    - LISP=ccl

addons:
  apt:
    packages:
      - libtidy-dev

install:
  - curl -L https://raw.githubusercontent.com/snmsts/roswell/master/scripts/install-for-ci.sh | sh

cache:
  directories:
    - $HOME/.roswell
    - $HOME/.config/common-lisp
    
script:
  # - echo '(handler-case (progn (ql:quickload :weblocks-test)
  #                              (weblocks-test:test-weblocks))
  #             (error () (princ "Error occured, returning 1")
  #                   (terpri)
  #                   (uiop:quit 1)))' | ros run && echo "TESTS ARE OK" || echo "TESTS ARE FAILED"
  - exit 1
  # - echo '(uiop:quit 1)' | ros run && echo "TESTS ARE OK" || echo "TESTS ARE FAILED"
  # - echo '(uiop:quit
  #            (or (ignore-errors
  #                        (progn (ql:quickload :weblocks-test)
  #                               (weblocks-test:test-weblocks)))
  #                1))' | ros run && echo "TESTS ARE OK" || echo "TESTS ARE FAILED"
