{
  "name": "CI",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    },
    "pull_request": null,
    "schedule": [
      {
        "cron": "0 10 * * 1"
      }
    ]
  },
  "jobs": {
    "run-tests": {
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "os": [
            "ubuntu-latest",
            "windoes-latest"
          ],
          "lisp": [
            "sbcl-bin",
            "ccl-bin"
          ]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "env": {
        "OS": "${{ matrix.os }}",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "${{ matrix.lisp }}"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v3"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@fix-test-ros",
          "with": {
            "asdf-system": "reblocks"
          }
        },
        {
          "name": "Run Tests",
          "uses": "40ants/run-tests@v2",
          "with": {
            "asdf-system": "reblocks",
            "coveralls-token": "\n${{ matrix.lisp == 'sbcl-bin' &&\n    matrix.os == 'ubuntu-latest' &&\n    matrix.quicklisp == 'ultralisp' &&\n    secrets.github_token }}"
          }
        }
      ]
    }
  }
}
