{
  "name": "CI",
  "on": {
    "push": {
      "branches": [
        "master"
      ]
    },
    "pull_request": null,
    "schedule": [
      {
        "cron": "0 10 * * 1"
      }
    ]
  },
  "jobs": {
    "run-tests": {
      "strategy": {
        "fail-fast": false,
        "matrix": {
          "os": [
            "windows-latest"
          ],
          "lisp": [
            "sbcl-bin"
          ]
        }
      },
      "runs-on": "${{ matrix.os }}",
      "env": {
        "OS": "${{ matrix.os }}",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "${{ matrix.lisp }}"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v3"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@fix-test-ros",
          "with": {
            "asdf-system": "reblocks"
          }
        },
        {
        "name": "Show path",
        "run": "env | sort"
        },
        {
        "name": "Show dir 0_0",
        "run": "ls -l C:/Users/runneradmin/ || true"
        },
        {
        "name": "Show dir 0",
        "run": "ls -l C:/Users/runneradmin/.roswell/lisp/quicklisp/bin || true"
        },
        {
        "name": "Show dir 0_1",
        "run": "ls -l C:/Users/runneradmin/.roswell/ || true"
        },
        {
        "name": "Show dir 0_3",
        "run": "which qlot || true"
        },
        {
        "name": "Show dir 0_3 2",
        "run": "ls - /mingw64/bin/ros || true"
        },
        {
        "name": "Show dir 0_4",
        "run": "which ros || true"
        },

        {
        "name": "Show dir 0_3 lispsh",
        "shell": "lispsh -eo pipefail {0}",
        "run": "ls - /mingw64/bin/ros || true"
        },
        {
        "name": "Show dir 0_4 lispsh",
        "shell": "lispsh -eo pipefail {0}",
        "run": "which ros || true"
        },


        {
        "name": "Show dir 1 1 1 1",
        "run": "ls -l /d/a/_temp/roswell || true"
        },
        {
        "name": "Show dir 2",
        "run": "ls -l ~/.qlot/bin || true"
        },
        {
        "name": "Show dir 3",
        "run": "ls -l .qlot/bin || true"
        },
        {
          "name": "Run Tests",
          "uses": "40ants/run-tests@v2",
          "with": {
            "asdf-system": "reblocks",
            "coveralls-token": "\n${{ matrix.lisp == 'sbcl-bin' &&\n    matrix.os == 'ubuntu-latest' &&\n    matrix.quicklisp == 'ultralisp' &&\n    secrets.github_token }}"
          }
        }
      ]
    }
  }
}
