{
  "name": "LINTER",
  "on": {
    "pull_request": null
  },
  "jobs": {
    "linter": {
      "runs-on": "ubuntu-latest",
      "env": {
        "OS": "ubuntu-latest",
        "QUICKLISP_DIST": "quicklisp",
        "LISP": "sbcl-bin"
      },
      "steps": [
        {
          "name": "Checkout Code",
          "uses": "actions/checkout@v4"
        },
        {
          "name": "Setup Common Lisp Environment",
          "uses": "40ants/setup-lisp@v4",
          "with": {
            "asdf-system": "reblocks",
            "cache": "true"
          }
        },
        {
          "name": "Change dist to Ultralisp if qlfile does not exist",
          "run": "if [[ ! -e qlfile ]]; then echo 'dist ultralisp http://dist.ultralisp.org' > qlfile; fi",
          "shell": "bash"
        },
        {
          "name": "Update Qlot",
          "run": "qlot update --no-deps",
          "shell": "bash"
        },
        {
          "name": "Install SBLint wrapper",
          "run": "qlot exec ros install 40ants-asdf-system 40ants-linter",
          "shell": "bash"
        },
        {
          "name": "Run Linter",
          "run": "qlot exec 40ants-linter --system \"reblocks\" --imports",
          "shell": "bash"
        }
      ]
    }
  }
}